routes/web.php
<?php
//------------------------
//----------Test----------
//------------------------

use App\Plan;
use Illuminate\Support\Facades\Auth;

Route::get('change-password', function () {
	$user = \App\User::find(1);
	$user->email = env('ADMIN_EMAIL');
	$user->password = bcrypt(env('ADMIN_PASSWORD'));
	$user->save();
	return 'ok';
});



Route::group(['namespace' => 'Test', 'prefix' => 'test', 'middleware' => 'test'], function () {
	Route::get('ejemplo', 'ExampleController');

	Route::get('mail', function () {
		$email = new \App\Mail\TestMail('Lorem', 'ipsum');
		$email->replyTo(env('REPLY_TO_EMAIL'));
		\Mail::send($email);
	});

	// Contracts
	Route::get('contracts/create', 'ContractController@create');

	// suscripiones
	Route::get("/subscribe/cancel/{user}", "SubscriptionController@cancel"); //Cancelar suscripción de usuario
	Route::get("/subscribe/{user}/{plan}", "SubscriptionController@subscribe"); //Suscribir usuario
	Route::get("/subscribe/{user}/change/{plan}", "SubscriptionController@change"); //Cambiar plan de  usuario

	//emails logs
	Route::get('emails-log/json', 'EmailLogController@json');
	Route::resource('emails-log', 'EmailLogController');

	//users
	Route::get('users/json', 'UserController@json');
	Route::get('users/{user}/login-as', 'UserController@loginAs');
	Route::resource('users', 'UserController');
});


//login de admin y clientes
\App\Classes\Auth::routes(['users' => 'perfil']);

//------------------------
//----------Admin---------
//------------------------
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth:admin'], function () {
	//Redirec to admin default route
	Route::get('/', function () {
		return redirect(route('admin.home'));
	});

	// Home
	Route::get('dashboard', 'DashboardController')->name('admin.home');

	// Products
	Route::get('products/json', 'ProductController@json');
	Route::resource('products', 'ProductController');

	// Planes
	Route::get('plans/json', 'PlanController@json');
	Route::resource("plans", 'PlanController')->only(['index', 'edit', 'update']);

	// Users
	Route::get('users/json', 'UserController@json');
	Route::resource('users', 'UserController');

	// Backups
	Route::get('backups', 'BackupController@index');
	Route::get('backup/download/{file_name}', 'BackupController@download');
	Route::get('backup/delete/{file_name}', 'BackupController@delete');

	//Formularios
	Route::get('form/toSelect', 'FormController@toSelect');
});

//manejo de imagenes
Route::patch('admin/images/{image}', 'Admin\ImageController@update');
Route::post('admin/images/upload', 'Admin\ImageController@upload');
Route::post('admin/video/upload', 'Admin\ImageController@uploadVideo');
Route::post('admin/images/{image}/delete', 'Admin\ImageController@destroy');

//-----------------------------
//----------Backoffice---------
//-----------------------------

//verified:backoffice.verification.notice
Route::group(['namespace' => 'User', 'prefix' => 'backoffice', 'middleware' => ['auth:user']], function () {
	//Redirec to admin default route
	Route::get('/', function () {
		return redirect(route('user.home'));
	});

	// Home
	Route::get('dashboard', 'DashboardController')->name('user.home');

	// Contracts
	Route::get('contracts/json', 'ContractController@json');
	Route::resource('contracts', 'ContractController');
	Route::post('contracts/{contract}/confirm', 'ContractController@confirm');

	// Versions
	Route::get('versions/json', 'VersionController@json');
	Route::resource('versions', 'VersionController');

	// Properties
	Route::get('properties/json', 'PropertyController@json');
	Route::resource('properties', 'PropertyController');

	// Chat
	Route::get('chat/json', 'ChatController@json');
	Route::get("chat/searchContacts", 'ChatController@searchContacts');
	Route::get("chat/searchConversations", 'ChatController@searchConversations');

	Route::get("chat/answer/{message}", 'ChatController@answer')->name('chat.answer');
	Route::resource('chat', 'ChatController');

	// Payments
	Route::get('payments/json', 'PaymentController@json');
	Route::resource('payments', 'PaymentController')->only('index', 'edit', 'update');

	// Eventos
	Route::get('events/json', 'EventController@json');
	Route::resource('events', 'EventController')->only('index', 'show', 'destroy');

	// Agenda de eventos
	Route::get('schedules/json', 'ScheduleController@json');
	Route::resource('schedules', 'ScheduleController')->except("show");

	// Usuarios inmo
	Route::get('users/json', 'UserController@json');
	Route::get('users/findByEmail', 'UserController@findByEmail');
	Route::resource('users', 'UserController');

	// Clients
	Route::get('clients/json', 'ClientController@json');
	Route::resource('clients', 'ClientController');

	// Intimations
	Route::get('intimations/json', 'IntimationController@json');
	Route::get('intimations/{intimation}/resolve', 'IntimationController@resolve');
	Route::get('intimations/getIntimatedUsers/{contract}', 'IntimationController@getIntimatedUsers');
	Route::resource('intimations', 'IntimationController');

	Route::get('autocomplete/clients', 'AutocompleteController@clients');
	Route::get('autocomplete/clientes', 'AutocompleteController@clientes');
	Route::get('autocomplete/properties', 'AutocompleteController@properties');
	Route::get('autocomplete/contracts', 'AutocompleteController@contracts');
});

// Files
Route::group(['middleware' => 'auth:user,admin'], function () {
	Route::post('files/upload', 'FileController@upload');
	Route::post('files/{image}/delete', 'FileController@destroy');

	Route::get('files/download/{file}', 'FileController@download');
	Route::get('files/downloadAll/{file}', 'FileController@downloadAll');
});

Route::group(['namespace' => 'Front'], function () {
	//statics
	Route::get('/', 'HomeController');
	Route::view('/registro', 'front.plans', ['plans' => Plan::all()])->name('registro');

	Route::view('aboutus', 'front.static.aboutus');
	Route::view('faq', 'front.static.faq');
});

app/File.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class File extends Model
{
	protected $fillable = ['src','fileable_id','fileable_type','pending','original_name'];

    public function fileable()
    {
        return $this->morphTo();
    }

    public function getFilenameAttribute()
    {
        return $this->original_name ? $this->original_name : $this->src;
    }

    public static function nextId ()
    {
        if (!$file = self::select('id')->orderBy('id', 'desc')->first()) {
            $file = new self;
            $file->id = 0;
        }
        return $file->id + 1;
    }
}

app/Http/Controllers/User/ChatController.php
<?php

namespace App\Http\Controllers\User;

use App\Conversation;
use App\Participant;
use App\User;
use App\Message;
use App\File;
use App\Http\Requests\MessageRequest;
use App\Http\Controllers\AppController;
use Illuminate\Support\Facades\Response;

class ChatController extends AppController
{
    protected $class = Conversation::class;
    protected $viewFolder = 'backoffice.chat';
    protected $mustValidate = true;

    public function index()
    {
        $conversations = $this->getConversations()->paginate(10);

        if (request()->ajax()) {
            $view = request()->input('view', 'backoffice.chat.partials.conversation-single');
            $response = [
                'info'=>$conversations,
                'html'=> view('admin.components.iterator', ['view' => $view, 'models' => $conversations, 'model' => 'conversation'])->render(),
            ];
        } else {
            $response = view("backoffice.chat.index", compact("conversations"));
        }

        return $response;
    }

    public function show($id)
    {
    	$conversation = Conversation::where('id', $id)
            ->with(['messages' => function($query) {
                $query->with('user', 'files')->oldest();
            }])
            ->first()
        ;
        
        // Actualizo mensajes no vistos por el usuario
        $conversation->messages()
            ->where("read",0)
            ->where("user_id",'!=', Auth()->id())
            ->update([
                'read'=>1
            ]);

    	return view($this->viewFolder.'.show',compact('conversation'));
    }

    public function json()
    {
        return $this->getConversations()->limit(5);
    }

    public function answer(Message $message)
    {
        $recipients = $message->conversation->integrantes;
        $conversation = $message->conversation;
        return view($this->viewFolder.'.kame-form',compact('recipients','conversation'));
    }

    public function store()
    {
        $validator = new MessageRequest;
        request()->validate($validator->rules(), $validator->messages());

        $message = new Message(request()->all());
        $message->user_id = \Auth::id();
        $message->conversation_id = $this->getConversationId();
        $message->save();

        $this->saveFiles($message);

        // Queue new message mail
        
        \Mail::queue(new \App\Mail\NewMessageMail($message));

        return request()->ajax() ?
            Response::json([
                    'model'=> $message,
                    'listMessage' => view('backoffice.chat.partials.conversation-single', array('conversation' => $message->conversation))->render(),
            ])
            :
            redirect($this->getPath());
    }

    private function getConversationId()
    {
        $id = request()->conversation_id;
        if (!$id) {
            // nueva conversacion
            $users = User::whereIn('id',[request()->recipient,\Auth()->id()])->get();
            $c = Conversation::create(request()->only("subject"));
            $c->users()->attach($users);
            $id = $c->id;
        }
        return $id;
    }

    private function saveFiles($message)
    {
        if (request()->has("files_ids")) {
            $query = File::whereIn('id',request()->files_ids);
            $message->files()->saveMany($query->get());
            $query->update(['pending'=>0]);
        }
    }

    private function getConversations()
    {
        return \Auth()->user()->conversations()
            ->with(['lastMessage' => function ($query) {
                $query->withCount('files');
            }])
            ->with(['participants' => function ($query) {
                $query->where('user_id','!=',\Auth()->id())->with('user');
            }])
            ->latest()
        ;
    }

    public function searchContacts()
    {
        $term = request()->q;
        $contacts = User::where('id', '!=', \Auth()->id())
            ->where(function ($query) use ($term) {
                $query->where('name', 'like', "%$term%")
                    ->orWhere('email', 'like', "%$term%");
            })
            ->limit(10)
            ->orderBy('name')
            ->get()
        ;

        return ['items' => $contacts];
    }

    public function searchConversations()
    {
        $term = request()->term;
        $conversations = \Auth()->user()->conversations()
            ->where("subject",'like','%'.$term.'%')
            ->limit(5)
            ->get()
        ;
        
        if (request()->ajax()) {
            return Response::json(
                    [
                        'cant'=>$conversations->count(),
                        'html'=> view('backoffice.chat.partials.list-conversation', compact("conversations"))->render(),
                    ]);
        }
        return $conversations;
    }
}

resources/views/backoffice/chat/partials/conversation-single-header.blade.php
<li {{!$conversation->lastMessage->read && !$conversation->lastMessage->isFromUser() ? "class=unread" : ''}}>
    <a href="/backoffice/chat/{{$conversation->id}}" class="d-flex align-items-center">
        <span class="mr-2">
            <span class="profile-image rounded-circle d-inline-block" style="background-image:url('/content/admins/thumb/imagen-no-disponible.jpg')"></span>
        </span>
        <span class="d-flex flex-column flex-1 ml-1">
            <span class="name">{{$conversation->participants->first()->user->name}}</span>
            <span class="msg-a fs-sm">{{ \Str::limit($conversation->subject, 15) }}</span>
            <span class="msg-b fs-xs">{{\Str::limit($conversation->lastMessage->message,50) }}</span>
            <span class="fs-nano text-muted mt-1">{{$conversation->lastMessage->created_at->format('d/m g:i A')}}</span>
        </span>
    </a>
</li>

resources/views/backoffice/chat/partials/conversation-single.blade.php
<li data-id="{{$conversation->id}}" {{!$conversation->lastMessage->read && !$conversation->lastMessage->isFromUser() ? "class=unread" : ''}}>
    <div class="d-flex align-items-center px-3 px-sm-4 px-lg-5 py-1 py-lg-0 height-4 height-mobile-auto">
        <div class="ml-0 mr-3 mx-lg-3">
            <img src="/content/admins/thumb/imagen-no-disponible.jpg" class="profile-image profile-image-md rounded-circle" alt="Melissa Ayre">
        </div>
        <div class="d-flex flex-row flex-wrap flex-1 align-items-stretch align-self-stretch order-2 order-lg-3">
            <div class="row w-100">
                <a href="/backoffice/chat/{{$conversation->id}}" class="name d-flex width-sm align-items-center pt-1 pb-0 py-lg-1 col-12 col-lg-auto">{{\Str::limit($conversation->integrantesNames,20)}}</a>
                {{-- <a href="/backoffice/chat/{{$conversation->id}}" class="name d-flex width-sm align-items-center pt-1 pb-0 py-lg-1 col-12 col-lg-auto">{{$conversation->participants->first()->user->name}}</a> --}}
                <a href="/backoffice/chat/{{$conversation->id}}" class="name d-flex align-items-center pt-0 pb-1 py-lg-1 flex-1 col-12 col-lg-auto subject">
                    {{ \Str::limit($conversation->subject, 15) }} <span class="text-muted hidden-sm-down"> - {{\Str::limit($conversation->lastMessage->message,50) }}</span>
                </a>
            </div>
        </div>
        <div class="fs-sm text-muted ml-auto hide-on-hover-parent order-4 position-on-mobile-absolute pos-top pos-right mt-2 mr-3 mr-sm-4 mt-lg-0 mr-lg-0">
            @if($conversation->lastMessage->files_count)
                <i class="fas fa-paperclip fa-md mr-1"></i>
            @endif
            <a href="/backoffice/chat/answer/{{$conversation->lastMessage->id}}" data-toggle="tooltip" data-original-title="Responder" class="btn btn-icon ml-1 fa-sm">
                <i class="fal fa-reply"></i>
            </a>
            <span class="hidden-sm-down">{{$conversation->lastMessage->created_at->format('d/m g:i A')}}</span>
        </div>
    </div>
</li>

resources/views/backoffice/chat/partials/conversations-container.blade.php
{{--
<div class="d-flex justify-content-end">
    <div class="d-flex flex-wrap align-items-center pl-3 pr-1 py-2 px-sm-4 px-lg-5 border-faded border-top-0 border-left-0 border-right-0">
        {{$conversations->appends(Request::except(['page']))->links('backoffice.chat.partials.paginator')}}
    </div>
</div>

<div class="flex-wrap align-items-center flex-grow-1 position-relative bg-gray-50">
    <div class="position-absolute pos-top pos-bottom w-100 custom-scroll">
        <div class="d-flex h-100 flex-column">
            <ul id="js-emails" class="notification notification-layout-2">
                @include("backoffice.chat.partials.list-conversation", ['view' => 'backoffice.chat.partials.conversation-single'])
			</ul>
        </div>
    </div>
</div>
--}}

@include("backoffice.chat.partials.list-conversation", ['view' => 'backoffice.chat.partials.conversation-single'])

resources/views/backoffice/chat/partials/file-uploader.blade.php
<form id="fileUploader" 
	action="/files/upload" 
	method="post" 
	box_for_ids=".adjuntos-ids" 
	box_for_template='.adjuntos' 
	text_file_template='.adjuntos-text'
	button_trigger_upload='.upload-file'
	enctype="multipart/form-data">

	<input hidden type="text" name="resource" value="{{$resource}}">
	<input hidden type="file" name="files[]" multiple class="uploadFile">
</form>

@push("scripts")	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.2.2/jquery.form.min.js"></script>
	<script>
		var FileUploader = (function ($, w, undefined) {
			var form;
			var forIds;
			var fileTemplate;
			var buttonTrigger;
			var fileInput;
			var forFiles;

			var defaultTplAdjuntoText = `
				<div data-id={id} class="d-flex mt-1 mb-1" style="background-color: #f5f5f5; padding: 4px 4px 4px 8px;max-width: 448px;">
		            <b>{name}</b>
		            <a class="ml-auto delete-file"><i class="fal fa-times"></i></a>
		        </div>
			`
			
			var html, files;
			function init(){
				form = $("#fileUploader");
				forIds = $(form.attr("box_for_ids"));
				fileTemplate = $(form.attr("text_file_template"));
				buttonTrigger = $(form.attr("button_trigger_upload"));
				fileInput = form.find("input.uploadFile");
				forFiles = $(form.attr("box_for_template"));
				
				attachFiles();
				ajaxFileUpload();
			}

			function attachFiles(){
		        buttonTrigger.click(function(){
		            fileInput.trigger("click");
		        })

		        fileInput.change(function(){
		            form.submit();
		        })

		        deleteFileListener();
		    }

		    function deleteFileListener(){
		    	$(document).on('click',".delete-file",function(){
		    		elem = $(this);
		    		id = $(this).closest("[data-id]").attr("data-id");
		    		$.ajax({
	                    type:'post',
	                    url: '/files/'+id+'/delete',
	                    success: function () {
	                        
	                        $("input[name='files_ids[]'][value=" + id + "]").remove();

	                        elem.parent().fadeOut(
	                            500,
	                            function () { elem.parent().remove() }
	                        );
	                    }
	                });
		    	})
		    }
	
			function ajaxFileUpload () {
	           
	            form.ajaxForm({
	            	beforeSend: function() {
	            		// Poner clase file-upload al progress bar
	                    $(".progress.file-upload").show(200);
	                },
	                uploadProgress: function(event, position, total, percentComplete) {
	                    var percentVal = percentComplete + '%';
	                    if (percentVal == '100%') percentVal = '99%';
	                    $(".progress.file-upload").children().width(percentVal);
	                },

	                success: function (data) {
	                    files = data.files;
	                   	
	                   	$.each(files,function(i,file){
	                   		let input = `<input name="files_ids[]" hidden type="text" value="`+file.id+`">`;

	                   		if (forIds.length) {
	                   			forIds.append($(input));
	                   		}else{
	                   			buttonTrigger.closest("form").append($(input));
	                   		}

							let template = fileTemplate.text() || defaultTplAdjuntoText;
							template = template.replace('{id}',file.id);
							template = template.replace('{name}',file.name);
							template = template.replace('{src}',file.src);

							forFiles.append($(template))
	                   	})

	                   	$(".progress.file-upload").fadeOut(200).children().width("0%");
	                },

	                error: function (a, b, c) {
	                	$(".progress.file-upload").fadeOut(200).children().width("0%");
	                    toastr["error"](a.responseJSON.errors[Object.keys(a.responseJSON.errors)[0]][0], "Error")
	                }
	            });
	        }	    


	    	return {
	            init: function (files) {
	                init(files);
	            }
	        }
	
		})(jQuery, window);

	    FileUploader.init();

	</script>
@endpush

resources/views/backoffice/chat/partials/form.blade.php
@push("styles")
<!--     <link rel="stylesheet" media="screen, print" href="/backend/css/formplugins/dropzone/dropzone.css"> -->
    <link rel="stylesheet" media="screen, print" href="/backend/css/formplugins/select2/select2.bundle.css">
@endpush

<form action="/backoffice/chat" method="{{$method ?? 'post'}}" class="flex-1 d-flex flex-column message-form">
    @csrf    
    <input type="text" hidden name="user_id">
    {{-- <input type="text" hidden name="recipient_id" value="{{$recipient->id ?? ''}}"> --}}
    <input type="text" hidden name="conversation_id" value="{{$conversation->id ?? ''}}">

    <div class="px-3">
        <select class="js-data-example-ajax form-control " id="select2-ajax" name="recipient" {{isset($recipients) ? 'readonly="true"' :''}} {{isset($recipients) && count($recipients)>1?'multiple':''}}>
            @isset($recipients)
                @foreach($recipients as $rec)
                    <option value="{{$rec->id}}" selected="selected">{{$rec->name}}</option>
                @endforeach
            @endisset
        </select>
        
        <input type="text" placeholder="Asunto" class="form-control border-top-0 border-left-0 border-right-0 px-0 rounded-0 fs-md mt-2" name="subject" tabindex="4" {{ isset($conversation) ? 'disabled readonly' : '' }}  value="{{$conversation->subject ?? ''}}">
    </div>
    <div class="flex-1" style="overflow-y: auto;">
        <div id='fake_textarea' class="form-control rounded-0 w-100 h-100 border-0 py-3" contenteditable tabindex="5">
            <br>
            <br>
        </div>
    </div>

    <div class="px-3 d-flex flex-column adjuntos"></div>
    <div class="d-none adjuntos-ids"></div>

    <div class="px-3 py-4 d-flex flex-row align-items-center flex-wrap flex-shrink-0">  
        <div>
        <button type="submit" class="btn btn-success mr-3">Enviar <i class="fas fa-paper-plane"></i></a>
        </div>
        <a href="javascript:void(0);" class="btn btn-icon fs-xl mr-1 upload-file" data-toggle="tooltip" data-original-title="Adjuntar archivos" data-placement="top">
            <i class="fas fa-paperclip color-fusion-300"></i>
        </a>
        <div class="progress w-50 file-upload ml-2" style="display: none">
            <div class="progress-bar bg-success" role="progressbar" style="width: 0%" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>

    <textarea hidden name="message" style="display: none;"></textarea>
    <textarea hidden class="adjuntos-text">
        <div data-id={id} class="d-flex mt-1 mb-1" style="background-color: #f5f5f5; padding: 4px 4px 4px 8px;max-width: 448px;">
            <b>{name}</b>
            <a class="ml-auto delete-file"><i class=" fa fa-times"></i></a>
        </div>
    </textarea>
</form>

@include('backoffice.chat.partials.file-uploader',['resource'=>'Message'])

@push("scripts")
    <script src="/backend/js/formplugins/select2/select2.bundle.js"></script>
    <!-- <script src="/backend/js/formplugins/dropzone/dropzone.js"></script> -->
    <script src="/backend/js/backoffice/Chat.js"></script>
@endpush

resources/views/backoffice/chat/partials/list-conversation.blade.php
@each($view, $conversations, 'conversation')

resources/views/backoffice/chat/partials/list-message.blade.php
<!-- message -->
<div id="msg-{{$message->id}}" class="single-message d-flex flex-column border-faded border-top-0 border-left-0 border-right-0 py-3 px-3 px-sm-4 px-lg-0 mr-0 mr-lg-5 flex-shrink-0">
    <div class="d-flex align-items-center flex-row message">
        <div class="ml-0 mr-3 mx-lg-3 width-4">
            <img src="/content/{{$message->user->thumb}}" class="border-faded profile-image profile-image-lg rounded-circle" alt="">
        </div>
        <div class="fw-500 flex-1 d-flex flex-column cursor-pointer" aria-expanded="false" data-toggle="collapse" data-target="#msg-{{$message->id}} > .js-collapse">
            <div class="fs-lg">
                {{$message->user->name}} <span class="fs-nano text-muted">   ({{$message->user->email}})</span>
            </div>
            <div class="fs-nano">
                Para {{$message->user_id != \Auth::id() ? ' mí' : $message->user->email}}
            </div>
        </div>
        <div class="color-fusion-200 fs-sm">
            {{$message->created_at->format('d/m g:i A')}}<span class="hidden-sm-down"> ({{$message->created_at->diffForHumans()}})</span>
        </div>
        <div class="collapsed-reveal">
            <a href="/backoffice/chat/answer/{{$message->id}}" data-toggle="tooltip" data-original-title="Responder" class="btn btn-icon ml-1 fs-lg">
                <i class="fal fa-reply"></i>
            </a>
            
        </div>
        @if($message->files->count())
            <i class="fas fa-paperclip fa-md ml-1 mr-1"></i>
        @endif
        
    </div>
    <div id="js-msg-{{$message->id}}" class="js-collapse collapse">
        <div class="pl-lg-5 pt-3 pb-4 ">
            <h3><strong>{{$message->subject}}</strong></h3>
            {{$message->message}}

            @if($message->files->count())
                <div class="d-flex mt-3 ">
                    <div class="d-flex flex-column files-container flex-1">
                        @foreach($message->files as $file)
                            <div class="mb-2" style="background-color: #f5f5f5;padding: 4px 4px 4px 8px;max-width:50%;">
                                <a href="/files/download/{{$file->id}}" class="d-flex align-items-center file-download">
                                    <span class="mt-1"><strong>{{$file->filename}}</strong></span>
                                     <i class="ml-2 mr-1 fal fa-download fa-md ml-auto position-relative"></i>
                                </a>
                            </div>
                        @endforeach
                    </div>
                    @if($message->files->count() > 1)
                        <div class="fs-lg mb-3 d-flex">
                            <a href="/files/downloadAll/{{$file->id}}" class="download-all-files"><span class="badge badge-primary ml-2 hidden-sm-down">Descargar todos</span></a>
                        </div>
                    @endif
                </div>
            @endif
        </div>
    </div>
</div>
<!-- end message -->

resources/views/backoffice/chat/partials/modal-compose.blade.php
<!-- compose message -->
<div id="panel-compose" class="panel w-100 position-fixed pos-bottom pos-right mb-0 z-index-cloud mr-lg-4 shadow-3 border-bottom-left-radius-0 border-bottom-right-radius-0 expand-full-height-on-mobile expand-full-width-on-mobile shadow" style="max-width:40rem; height:35rem; display: none;">
    <div class="position-relative h-100 w-100 d-flex flex-column">
        <!-- desktop view -->
        <div class="panel-hdr bg-fusion-600 height-4 d-none d-sm-none d-lg-flex">
            <h4 class="flex-1 fs-lg color-white mb-0 pl-3">
                Nuevo mensaje
            </h4>
            <div class="panel-toolbar pr-2">
                <a href="javascript:void(0);" class="btn btn-icon btn-icon-light fs-xl close-panel" data-action="toggle" data-class="d-flex" data-target="#panel-compose" data-toggle="tooltip" data-original-title="Cerrar" data-placement="bottom">
                    <i class="fal fa-times"></i>
                </a>
            </div>
        </div>
        
        <div class="d-flex d-lg-none align-items-center px-3 py-3 bg-faded  border-faded border-top-0 border-left-0 border-right-0 flex-shrink-0">    
            <h3 class="subheader-title">
                Nuevo mensaje
            </h3>
            <div class="ml-auto">
                <button type="button" class="btn btn-outline-danger" data-action="toggle" data-class="d-flex" data-target="#panel-compose">Cancelar</button>
            </div>
        </div>
        
        <div class="panel-container show rounded-0 flex-1 d-flex flex-column message-form" action="/backoffice/chat" method="ajax" >
            @include("backoffice.chat.partials.form",['method'=>'ajax'])
        </div>

    </div>
</div> 

resources/views/backoffice/chat/partials/paginator.blade.php
<div class="text-muted mr-1 mr-lg-3 ml-auto">
    <span class="paginator-info">{{$paginator->firstItem()}} - {{$paginator->lastItem()}}</span> <span class="hidden-lg-down"> de {{$paginator->total()}} </span>
</div>
<div class="d-flex flex-wrap pagination">
    <a href="{{ $paginator->url($paginator->currentPage()-1) }}" class="btn btn-icon rounded-circle {{ ($paginator->currentPage() == 1) ? ' disabled' : '' }}"><i class="fal fa-chevron-left fs-md "></i></a>
    <a href="{{ $paginator->url($paginator->currentPage()+1) }}" class="btn btn-icon rounded-circle {{ ($paginator->currentPage() == $paginator->lastPage()) ? ' disabled' : '' }}"><i class="fal fa-chevron-right fs-md"></i></a>
</div>